config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {registrations: "admins/registrations"}

  root to: "posts#index"

  resources :posts, only: [:index, :show]
  resources :works, only: [:index]

  namespace :admins do
    root to: "posts#index"

    resources :posts
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_many :posts

  devise :database_authenticatable, :recoverable, :registerable, :rememberable, 
         :timeoutable, :validatable

  def active_for_authentication?
    super && approved
  end

  def inactive_message
    if !approved
      :not_approved
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId

  belongs_to :admin

  validates :title, presence: true

  friendly_id :title, use: :slugged
  has_attached_file(
    :feature_image,
    default_url: "/images/:style/missing.png",
    storage: :dropbox,
    dropbox_credentials: Rails.root.join("config/dropbox.yml")
  )
  validates_attachment_content_type(
    :feature_image,
    content_type: /\Aimage\/.*\Z/
  )
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < AdminsController 
  def index
    @posts = Post.friendly.order("published_at ASC")
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    
    if @post.save
      redirect_to admins_posts_path
    else
      render "new"
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])

    if @post.update(post_params)
      redirect_to :back
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy
    
    redirect_to admins_posts_path 
  end

  private

  def post_params
    params.require(:post).permit(
      :admin_id,
      :body,
      :feature_image,
      :published_at,
      :published,
      :slugged,
      :title,
    )
  end
end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < ::Devise::RegistrationsController
  layout "admin"

  def account_update_params
    params.require(:admin).permit(:first_name,
                                  :last_name,
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :current_password)
  end

  def after_update_path_for(resource)
    edit_admin_registration_path(resource)
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!
  skip_before_action:verify_authenticity_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(admins)
    admins_posts_path(admins)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.friendly.where(published: true).order(published_at: :desc).limit(10)
  end

  def show
    post = Post.friendly.find(params[:id])
    @post = PostPresenter.new(post)
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hero_helper.rb
module HeroHelper
  def active_words_link
    if params[:controller] == "posts"
      "active"
    end
  end

  def active_works_link
    if params[:controller] == "works"
      "active"
    end
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def navigation_state
    session[:navigation_state]
  end
end

app/helpers/post_helper.rb
module PostHelper
  def post_author_gravatar(post)
    if(post.admin_email)
      content_tag :div, class: "gravatar" do
        gravatar_tag post.admin_email
      end
    end
  end

  def post_author_full_name(post, class_name)
    if(post.author_full_name)
      content_tag :div, class: class_name do
        "By #{post.author_full_name}"
      end
    end
  end
end

app/views/admins/posts/_form.html.haml
= simple_form_for [:admins, @post] do |f|
  %section.layout
    %header.content
      = f.input :title,
          label: false,
          input_html: { class: "input--line edit-post__title-input" }

  %section.layout.layout--white
    %section.content
      %aside.edit-post__meta
        = f.input :published,
            as: :boolean,
            wrapper_html: { class: "checkbox--x-o" },
            boolean_style: :inline
        = f.file_field :feature_image,
            data: { "image-select" => true }
        = f.input :published_at, as: :date
        = f.association :admin,
            value_method: :id,
            label_method: :email,
            label: "Author"
        %label
          Main Image
        = image_tag @post.feature_image.url,
          class: "edit-post__image",
          data: { "image-select-trigger" => true }

        = f.button :submit, class: "button button--cta"

      %article
        = f.input :body,
          label: false,
          input_html: { class: "edit-post__body",
            data: { "flexible-textarea" => true } }

app/views/admins/posts/edit.html.haml
%main
  = render "form"

app/views/admins/posts/index.html.haml
%main.layout
  %section.content
    %header.posts__header
      %h1
        All Posts
      = link_to new_admins_post_path, class: "button button--cta" do
        = t(".new_post")
        %i.fa.fa-plus
    %table.posts-table
      %tr
        %th.posts-table__col
          Title
        %th.posts-table__col
          Published At
        %th.posts-table__col
          Published
        %th.posts-table__col
      - @posts.each do |post|
        - post = PostPresenter.new(post)
        %tr{ id: "post_#{post.id}" }
          %td.posts-table__col
            = link_to edit_admins_post_path(post) do
              = post.title
          %td.posts-table__col
            = post.published_at_formatted
          %td.posts-table__col
            = post.published
          %td.posts-table__col
            = link_to 'Delete', admins_post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' }

app/views/admins/posts/new.html.haml
%main
  = render "form"

app/views/admins/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)

- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)

- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)

- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)

app/views/application/_favicon.html.haml
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="favicon-152.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="favicon-144.png">
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="favicon-120.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="favicon-114.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="favicon-72.png">
<link rel="apple-touch-icon-precomposed" href="favicon-57.png">

app/views/application/_flashes.html.haml
#flash
  - flash.each do |key, value|
    %div{class: "flash-#{key}"}
      = value

app/views/application/_hero.html.haml
.layout.hero-landing
  .hero-intro
    = image_tag "whoa.svg", class: "logo"
    .hero-intro__links
      = link_to t(".words"),
        posts_path(anchor: "words"),
        class: "button button--hero #{active_words_link}"
      = link_to t(".work"),
        works_path(anchor: "work"),
        class: "button button--hero #{active_works_link}"

app/views/application/_javascript.html.haml
= javascript_include_tag :application
= yield :javascript
- if Rails.env.test?
  = javascript_tag do
    $.fx.off = true;
    $.ajaxSetup({ async: false });

app/views/application/_navigation.html.haml
%header.navigation
  %a{class: "navigation__trigger", href: "#"}
    = inline_svg "icon-menu.svg", class: "menu"
    = inline_svg "icon-close.svg", class: "close"
    %span
      Menu
  %nav.navigation__drawer
    %ul
      %li
        = link_to "Words",
            posts_path,
            anchor: "words",
            class: "navigation__link"
      %li
        = link_to "Works",
            works_path,
            anchor: "words",
            class: "navigation__link"

      - if admin_signed_in?
        %li
          = link_to t(".all_posts"),
            admins_posts_path,
            class: "navigation__link navigation__link--new-section"
        %li
          = link_to "Account Settings",
            edit_admin_registration_path,
            class: "navigation__link"
        %li
          = link_to "Logout",
            destroy_admin_session_path,
            method: :delete,
            class: "navigation__link"

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "NOODP", name: "ROBOTS"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title
      = "#{title} | Admin"
    = stylesheet_link_tag :admin, media: "all"
    = javascript_include_tag :admin
    = csrf_meta_tags
  %body{class: "admin #{body_class}"}
    = render "flashes"
    = render "navigation"
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "NOODP", name: "ROBOTS"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title
      = title
    = render "favicon"
    = stylesheet_link_tag :application, :media => "all"
    = csrf_meta_tags
  %body{class: body_class}
    = render "flashes"
    = render "application/navigation"
    = yield
    = render "javascript"

app/views/posts/_post_summary.haml
%li
  %article
    %header
      = image_tag post.feature_image.url, class: "post__image post__image--thumbnail"
      = link_to post do
        %h1.post__title
          = post.title
      .post__byline
        = post_author_full_name(post, class: "post__byline__author")
        %small.post__byline__date
          = post.published_at_fulldate

    %section
      .post__body.post__body--summary
        = strip_tags(post.body_summary_html)

  .post-list__read-more
    = link_to post, class: "button" do
      read more

app/views/posts/index.html.haml
= render "hero"

%main.layout#words
  %section.posts--list
    %ul
      - @posts.each do |post|
        = render partial: "post_summary",
          locals: { post: PostPresenter.new(post) }

app/views/posts/show.html.haml
%main.layout
  %article
    %header.content
      = image_tag @post.feature_image.url, class: "post__image"
      %h1.post__title.post__title--large
        = @post.title
      .post__byline
        = post_author_gravatar(@post)
        = post_author_full_name(@post, class: "post__byline__author")
        %small.post__byline__date
          = @post.published_at_fulldate
    %section.content.content--medium
      .post__body.post__body--full
        = preserve do
          = raw @post.body_as_string

app/views/welcome/index.html.haml
%main.layout
  .layout-hero--cover
    .hero-intro
      = image_tag "whoa.svg", class: "logo"
      %form
        %input.hero-search{ type: "text" }
    .hero-background

  %section.posts--list
    %ul
    - @posts.each do |post|
      - post = PostPresenter.new(post)
      %li
        %article
          = image_tag post.feature_image.url, class: "post__feature-thumbnail"
          = link_to post do
            %h2.post__title
              = post.title
          .post__byline
            .post__byline__author
              = "By #{post.author_full_name}"
            .post__byline__date
              = post.published_at_fulldate
          .post__body.post__body--summary
            = strip_tags(post.body_summary_html)
          %div.post__read-more
            = link_to post, class: "button" do
              read more

app/views/works/index.html.haml
= render "hero"

%main.layout
  %section.content
    %h1
      = t(".heading")

    %ul.works-list
      %li.work
        = link_to("http://prefab-patterns-marketplace.herokuapp.com", target: "_blank") do
          = image_tag "work/prefab-landing-page.png"
      %li.work
        = link_to("https://github.com/jasonramirez/prefab-patterns", target: "_blank") do
          = image_tag "work/prefab-gem.png"